export interface E2EScenario {
  id: number;
  title: string;
  prompt: string;
  setup: string;
  expectedBehavior: string;
  failureIndicates: "resolver" | "planner" | "runtime" | "ui_stale_state" | "config_auth";
  manualIntervention: boolean;
  seed: boolean;
}

export const e2eScenarios: E2EScenario[] = [
  {
    id: 1,
    title: "Login gate after valid plan",
    prompt: "Continue the task after the login page appears.",
    setup: "Runner connected, active browser session, authentication expires mid-run.",
    expectedBehavior: "Run transitions to waiting_for_user_action with a visible login blocker and takeover path.",
    failureIndicates: "runtime",
    manualIntervention: true,
    seed: true,
  },
  {
    id: 2,
    title: "OAuth popup steals focus",
    prompt: "Complete sign-in and continue after an OAuth popup opens.",
    setup: "Popup-capable auth flow and second browser surface.",
    expectedBehavior: "Planner/runtime tracks the popup and preserves active run context.",
    failureIndicates: "runtime",
    manualIntervention: true,
    seed: false,
  },
  {
    id: 3,
    title: "DOM refresh invalidates refs",
    prompt: "Click the primary action after the page refreshes.",
    setup: "DOM re-renders between observation and action.",
    expectedBehavior: "The system replans from fresh evidence instead of using stale refs.",
    failureIndicates: "planner",
    manualIntervention: false,
    seed: true,
  },
  {
    id: 4,
    title: "Ambiguous duplicate labels across surfaces",
    prompt: "Choose the visible Continue button in the modal.",
    setup: "Page and modal both contain Continue buttons.",
    expectedBehavior: "Visible-state evidence scopes the action to the foreground surface.",
    failureIndicates: "resolver",
    manualIntervention: false,
    seed: false,
  },
  {
    id: 5,
    title: "Foreground composer ignored",
    prompt: "Send the message in the open composer.",
    setup: "A drawer composer is already open in the foreground.",
    expectedBehavior: "Planner observes the open composer first, not the full page body.",
    failureIndicates: "planner",
    manualIntervention: false,
    seed: true,
  },
  {
    id: 6,
    title: "Source content mutates during cross-app transfer",
    prompt: "Copy the latest Gmail body and send it in WhatsApp.",
    setup: "Source email content changes after extraction before send.",
    expectedBehavior: "Verification catches the mismatch and requests a safe retry or re-extract.",
    failureIndicates: "runtime",
    manualIntervention: false,
    seed: false,
  },
  {
    id: 7,
    title: "Schedule intent with attached browser session",
    prompt: "Schedule this for tomorrow even though the browser is open.",
    setup: "Ready browser session and schedule-like prompt.",
    expectedBehavior: "Resolver chooses scheduled execution without hijacking the live browser.",
    failureIndicates: "resolver",
    manualIntervention: false,
    seed: true,
  },
  {
    id: 8,
    title: "Immediate browser task misread as schedule",
    prompt: "Open Gmail now and send this once the page is visible.",
    setup: "Timing language is ambiguous.",
    expectedBehavior: "Resolver prefers immediate browser execution with visible-state dependence.",
    failureIndicates: "resolver",
    manualIntervention: false,
    seed: false,
  },
  {
    id: 9,
    title: "Sensitive action approval after partial progress",
    prompt: "Approve and continue when the final sensitive step is ready.",
    setup: "Run completes preparatory steps before sensitive action gating.",
    expectedBehavior: "Run pauses with Needs confirmation and resumes safely after approval.",
    failureIndicates: "runtime",
    manualIntervention: true,
    seed: true,
  },
  {
    id: 10,
    title: "Manual intervention mutates page before resume",
    prompt: "Resume after I fixed the page manually.",
    setup: "Human takeover changes the DOM and active page state.",
    expectedBehavior: "Resume path replans from current evidence instead of continuing stale steps.",
    failureIndicates: "planner",
    manualIntervention: true,
    seed: false,
  },
  {
    id: 11,
    title: "Rate limit retry loop",
    prompt: "Keep going after the model quota is hit.",
    setup: "Runtime model returns retriable rate-limit errors.",
    expectedBehavior: "UI shows retry countdown and last event instead of indefinite running.",
    failureIndicates: "ui_stale_state",
    manualIntervention: false,
    seed: true,
  },
  {
    id: 12,
    title: "Runner disconnect and reconnect",
    prompt: "Continue after the runner reconnects.",
    setup: "Runner websocket drops during an active run.",
    expectedBehavior: "Session status changes to disconnected, then browser attached again on reconnect.",
    failureIndicates: "config_auth",
    manualIntervention: false,
    seed: true,
  },
  {
    id: 13,
    title: "Runtime reachable but browser session missing",
    prompt: "Retry the task with no attached browser.",
    setup: "Runtime /ready succeeds but browser session no longer exists.",
    expectedBehavior: "Run blocks with Waiting for browser instead of hanging.",
    failureIndicates: "runtime",
    manualIntervention: false,
    seed: false,
  },
  {
    id: 14,
    title: "Backgrounded browser stalls event cadence",
    prompt: "Keep monitoring the page while the browser is backgrounded.",
    setup: "Browser is throttled in the background.",
    expectedBehavior: "UI exposes stale event timing and reconnect behavior.",
    failureIndicates: "ui_stale_state",
    manualIntervention: false,
    seed: false,
  },
  {
    id: 15,
    title: "Post-submit verification fails",
    prompt: "Submit the form and verify it succeeded.",
    setup: "Click succeeds but success state never appears.",
    expectedBehavior: "Run surfaces verification failure instead of success.",
    failureIndicates: "planner",
    manualIntervention: false,
    seed: true,
  },
  {
    id: 16,
    title: "Navigation after submit causes false completion",
    prompt: "Submit and wait until the confirmation page is visible.",
    setup: "Submit triggers navigation with stale previous-page evidence.",
    expectedBehavior: "Completion waits for new-page verification evidence.",
    failureIndicates: "planner",
    manualIntervention: false,
    seed: false,
  },
  {
    id: 17,
    title: "Multiple similar inbox targets",
    prompt: "Open the first matching thread and reply in the visible inbox.",
    setup: "Several visually similar inbox/chat targets.",
    expectedBehavior: "Resolver and planner use visible-state and disambiguation evidence.",
    failureIndicates: "resolver",
    manualIntervention: false,
    seed: true,
  },
  {
    id: 18,
    title: "Cross-app visible-state transfer",
    prompt: "Copy from the visible Gmail thread and paste it into the visible Slack composer.",
    setup: "Two apps and both rely on current visible state.",
    expectedBehavior: "Task shape marks cross-app transfer plus visible-state dependence.",
    failureIndicates: "resolver",
    manualIntervention: false,
    seed: false,
  },
  {
    id: 19,
    title: "Takeover lock conflicts with automated resume",
    prompt: "Resume while another actor still holds takeover lock.",
    setup: "Session controller lock belongs to a different actor.",
    expectedBehavior: "UI and backend expose takeover-active state instead of silently resuming.",
    failureIndicates: "config_auth",
    manualIntervention: true,
    seed: false,
  },
  {
    id: 20,
    title: "Incident emitted but UI could look like running",
    prompt: "Continue after an incident is reported.",
    setup: "Runtime emits incident without immediate terminal run state.",
    expectedBehavior: "Inline run card shows blocking reason, not a generic running badge.",
    failureIndicates: "ui_stale_state",
    manualIntervention: false,
    seed: true,
  },
];
